cities: transport_ch.osm

maxDist: 800

order:
    switch.time: 10 # minutes to switch from one route to another
    walk.speed: 6   # minutes per km
    stop.time: 2    # minutes between stops, average

    merge.wait.threshold: 5
