cities:
	chernivtsi: transport_ch.osm

maxDist: 2000 #2km

order.switch.time: 10 # minutes to switch from one route to another
order.walk.speed: 6   # minutes per km
order.stop.time: 2    # minutes between stops, average
